###############################################################
# TRPV1 STRUCTURAL PIPELINE
# Script: 06b_compute_helix_angles_v3.R
# Author: DenyCB
# Purpose:
# Compute helix–helix and helix–pore angles from axes files
# generated by script 06a.
#
# Inputs:
# output/angles/axes_<system>_repX.rds
#
# Outputs:
# output/angles/angle_csv/
# output/angles/angle_summary/
# output/angles/graphics/
#
###############################################################

cat("\n====================================================\n")
cat("[", Sys.time(), "] Starting script 06b_compute_helix_angles_v3.R\n")
cat("====================================================\n\n")

###############################################################
# 0 — LIBRARIES
###############################################################

suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(zoo)
  library(stringr)
})

###############################################################
# 1 — USER SETTINGS
###############################################################

# frame -> time
frame_to_ns <- 0.1

# smoothing
apply_smoothing <- TRUE
smooth_window <- 5

###############################################################
# GRAPHICS SETTINGS
###############################################################

plot_title_size <- 16
axis_title_size <- 13
axis_text_size <- 11

legend_position <- "right"
show_legend <- TRUE

replica_line_width <- 0.5
mean_line_width <- 1.3

replica_colors <- c(
  rep1 = "#6BAED6",
  rep2 = "#74C476",
  rep3 = "#FB6A4A"
)

mean_color <- "black"

###############################################################
# 2 — HELIX PAIRS TO ANALYZE
###############################################################

helix_pairs_intra <- list(
  c("S4","Linker",0), c("Linker","S5",0), c("Linker","S6",0), c("S6","TRPh",0)
)

helix_pairs_inter <- list(
  #c("S4","S4",2), c("S3","S5",1), c("S3","S5",3),c("S2","S5",3), c("S2","S5",1), c("S3","S6",3),c("S3","S6",1)
)

helix_tilt <- list(
  
  "S4"
)

###############################################################
# 3 — PATHS
###############################################################

axes_dir <- "output/angles_helices/angles"

csv_dir <- "output/angles_helices/angles/angle_csv"
summary_dir <- "output/angles_helices/angles/angle_summary"
plot_dir <- "output/angles_helices/angles/graphics2"

dir.create(csv_dir, recursive=TRUE, showWarnings=FALSE)
dir.create(summary_dir, recursive=TRUE, showWarnings=FALSE)
dir.create(plot_dir, recursive=TRUE, showWarnings=FALSE)

cat(axes_dir)
cat(csv_dir)
cat(summary_dir)
cat(plot_dir)

###############################################################
# 4 — UTILITY FUNCTIONS
###############################################################

cat("[", Sys.time(), "] Loading helper functions\n")

# angle between vectors
angle_between <- function(v1,v2){
  
  dot <- sum(v1*v2)
  
  a1 <- sqrt(sum(v1^2))
  a2 <- sqrt(sum(v2^2))
  
  cosang <- abs(dot/(a1*a2))
  
  cosang <- min(1,max(-1,cosang))  # estabilidad numérica
  
  ang <- acos(cosang)
  
  return(ang*180/pi)
}

# smoothing
smooth_series <- function(x){
  
  if(!apply_smoothing) return(x)
  
  return(zoo::rollmean(x,
                       k=smooth_window,
                       fill=NA,
                       align="center"))
}

###############################################################
# CHAIN OFFSET FUNCTION
###############################################################

chains <- c("A","B","C","D")

get_chain_pair <- function(chain, offset){
  
  offset <- as.integer(offset)
  
  if(offset == 0) return(chain)
  
  idx <- which(chains == chain)
  
  new <- ((idx - 1 + offset) %% 4) + 1
  
  return(chains[new])
}

###############################################################
# PARSE FILE NAME
###############################################################

parse_filename <- function(file){
  
  name <- basename(file)
  
  name <- str_remove(name,"axes_")
  name <- str_remove(name,".rds")
  
  parts <- str_split(name,"_",simplify=TRUE)
  
  structure <- parts[1]
  mutant <- parts[2]
  replica <- parts[3]
  
  system <- paste(structure,mutant,sep="_")
  
  return(list(
    system=system,
    replica=replica
  ))
}

###############################################################
# 5 — LOAD AXES FILES
###############################################################

cat("[", Sys.time(), "] Searching axes files\n")

axes_files <- list.files(
  axes_dir,
  pattern="axes_.*rds$",
  full.names=TRUE
)

cat("Found",length(axes_files),"files\n")

###############################################################
# 6 — BUILD PAIR DEFINITIONS
###############################################################

pair_definitions <- list()

# intra
for(p in helix_pairs_intra){
  
  name <- paste0(p[1],"_",p[2])
  
  pair_definitions[[name]] <- list(
    h1=p[1],
    h2=p[2],
    offset=0,
    type="helix"
  )
}

# inter
for(p in helix_pairs_inter){
  
  name <- paste0(p[1],"_",p[2],"_",p[3])
  
  pair_definitions[[name]] <- list(
    h1=p[1],
    h2=p[2],
    offset=p[3],
    type="helix"
  )
}

# tilt
for(h in helix_tilt){
  
  name <- paste0("tilt_",h)
  
  pair_definitions[[name]] <- list(
    h1=h,
    h2="PORE_AXIS",
    offset=0,
    type="tilt"
  )
}

###############################################################
# 7 — MAIN COMPUTATION
###############################################################

cat("[",Sys.time(),"] Starting angle calculations\n")

all_data <- list()

for(file in axes_files){
  
  info <- parse_filename(file)
  
  system <- info$system
  replica <- info$replica
  
  cat("[",Sys.time(),"] Processing",system,replica,"\n")
  
  axes <- readRDS(file)
  
  nframes <- nrow(axes[[1]])
  
  time_ns <- seq(0,(nframes-1)*frame_to_ns,frame_to_ns)
  
  for(pair_name in names(pair_definitions)){
    
    p <- pair_definitions[[pair_name]]
    
    for(chain in chains){
      
      chain2 <- get_chain_pair(chain,p$offset)
      
      h1_name <- paste(chain,p$h1,sep="_")
      
      if(p$type=="tilt"){
        
        h2_name <- "PORE_AXIS"
        
      }else{
        
        h2_name <- paste(chain2,p$h2,sep="_")
        
      }
      
      v1 <- axes[[h1_name]]
      
      v2 <- axes[[h2_name]]
      
      angles <- numeric(nframes)
      
      for(i in 1:nframes){
        
        angles[i] <- angle_between(v1[i,],v2[i,])
        
      }
      
      angles <- smooth_series(angles)
      
      df <- data.frame(
        system = system,
        replica = replica,
        pair = pair_name,
        chain_pair = paste(chain,chain2,sep="_"),
        frame = 1:nframes,
        time_ns = time_ns,
        angle = angles
      )
      
      all_data[[length(all_data)+1]] <- df
      
    }
    
  }
  
}

angles_df <- bind_rows(all_data)

###############################################################
# 8 — SAVE TIDY CSV
###############################################################

cat("[",Sys.time(),"] Writing CSV files\n")

pairs <- unique(angles_df$pair)

for(p in pairs){
  
  sub <- angles_df %>% filter(pair==p)
  
  dir.create(file.path(csv_dir,p),showWarnings=FALSE)
  
  write.csv(
    sub,
    file.path(csv_dir,p,paste0("angles_",p,".csv")),
    row.names=FALSE
  )
}

###############################################################
# 9 — SUMMARY CSV
###############################################################

summary_df <- angles_df %>%
  group_by(system,replica,pair) %>%
  summarise(
    mean_angle=mean(angle,na.rm=TRUE),
    sd_angle=sd(angle,na.rm=TRUE),
    .groups="drop"
  )

write.csv(
  summary_df,
  file.path(summary_dir,"angle_summary.csv"),
  row.names=FALSE
)

###############################################################
# 10 — GLOBAL RANGES
###############################################################

cat("[",Sys.time(),"] Computing global axis ranges\n")

ranges <- angles_df %>%
  group_by(pair) %>%
  summarise(
    ymin=min(angle,na.rm=TRUE),
    ymax=max(angle,na.rm=TRUE)
  )

###############################################################
# 11 — PLOT GENERATION
###############################################################

cat("[",Sys.time(),"] Generating plots\n")

systems <- unique(angles_df$system)

for(p in pairs){
  
  range <- ranges %>% filter(pair==p)
  
  ymin <- range$ymin
  ymax <- range$ymax
  
  dir.create(file.path(plot_dir,p),showWarnings=FALSE)
  
  for(sys in systems){
    
    sub <- angles_df %>%
      filter(pair==p,system==sys)
    
    mean_line <- sub %>%
      group_by(time_ns) %>%
      summarise(mean_angle=mean(angle,na.rm=TRUE))
    
    g <- ggplot(sub,
                aes(x=time_ns,
                    y=angle,
                    group=interaction(replica,chain_pair),
                    color=replica)) +
      
      geom_line(size=replica_line_width,alpha=0.7) +
      
      geom_line(data=mean_line,
                aes(x=time_ns,y=mean_angle),
                inherit.aes=FALSE,
                color=mean_color,
                size=mean_line_width)
    
    g <- g +
      scale_color_manual(values=replica_colors) +
      coord_cartesian(ylim=c(ymin,ymax)) +
      labs(
        title=paste(sys,p),
        x="Time (ns)",
        y="Angle (degrees)"
      ) +
      theme_bw() +
      theme(
        plot.title=element_text(size=plot_title_size),
        axis.title=element_text(size=axis_title_size),
        axis.text=element_text(size=axis_text_size),
        legend.position=if(show_legend) legend_position else "none"
      )
    
    ggsave(
      filename=file.path(plot_dir,p,paste0(sys,"_",p,".png")),
      plot=g,
      width=7,
      height=5,
      dpi=300
    )
    
  }
  
}
###############################################################
# 12 — GLOBAL COMPARISON PLOTS (MEAN PER CONDITION)
###############################################################

cat("[",Sys.time(),"] Generating global comparison plots\n")

# carpeta donde irán
comparison_dir <- file.path(plot_dir,"global_means")

dir.create(comparison_dir, showWarnings=FALSE)

pairs <- unique(angles_df$pair)

for(p in pairs){
  
  sub <- angles_df %>%
    filter(pair==p) %>%
    
    # 🔴 NUEVO: descomponer nombre del sistema original
    mutate(
      pdb = sub("^(7LP9|7LPB|7LPC)_.*", "\\1", system),
      mutant = sub("^(7LP9|7LPB|7LPC)_", "", system),
      condition = case_when(
        pdb=="7LP9" ~ "Apo",
        pdb=="7LPB" ~ "Cap",
        pdb=="7LPC" ~ "Heat",
        TRUE ~ pdb
      ),
      system_label = paste(mutant, condition)
    )
  
  # promedio entre replicas y subunidades
  mean_df <- sub %>%
    group_by(system,time_ns,system_label,mutant,condition) %>%
    summarise(
      mean_angle = mean(angle,na.rm=TRUE),
      .groups="drop"
    ) %>%
    
    # 🔴 NUEVO: ordenar leyenda
    mutate(
      system_label = factor(
        system_label,
        levels = c(
          "WT Apo","WT Cap","WT Heat",
          "W426A Apo","W426A Cap","W426A Heat",
          "W697A Apo","W697A Cap","W697A Heat",
          "Y441A Apo","Y441A Cap","Y441A Heat"
        )
      )
    )
  
  # obtener rango global
  range <- ranges %>% filter(pair==p)
  
  ymin <- range$ymin
  ymax <- range$ymax
  
  g <- ggplot(mean_df,
              aes(x=time_ns,
                  y=mean_angle,
                  color=mutant,
                  linetype=condition,
                  group=system_label)) +
    
    geom_line(size=0.6) +
    
    coord_cartesian(ylim=c(ymin,ymax)) +
    
    labs(
      title=paste("Mean comparison:",p),
      x="Time (ns)",
      y="Angle (degrees)",
      color="Mutant",
      linetype="Condition"
    ) +
    
    scale_color_manual(
      values=c(
        "WT"="black",
        "W426A"="orange",
        "W697A"="green4",
        "Y441A"="purple"
      ),
      breaks=c("WT","W426A","W697A","Y441A")
    ) +
    
    scale_linetype_manual(
      values=c(
        "Apo"="solid",
        "Cap"="22",
        "Heat"="11"
      ),
      breaks=c("Apo","Cap","Heat")
    ) +
    
    theme_bw() +
    
    theme(
      plot.title=element_text(size=plot_title_size),
      axis.title=element_text(size=axis_title_size),
      axis.text=element_text(size=axis_text_size),
      legend.position="right"
    )
  
  ggsave(
    filename=file.path(comparison_dir,
                       paste0("comparison_",p,".png")),
    plot=g,
    width=7,
    height=5,
    dpi=300
  )
  
}
cat("\n====================================================\n")
cat("[", Sys.time(), "] Script 06b finished successfully\n")
cat("====================================================\n")