###############################################################
# TRPV1 STRUCTURAL PIPELINE
# Script: 06d_violin_histograms_from_csv.R
# Author: DenyCB
# Purpose:
# Build violin plots and mutant-panel histograms from all
# angle CSV files generated by script 06b.
#
# Uses only data from time_ns >= 10
#
###############################################################

cat("\n====================================================\n")
cat("[", Sys.time(), "] Starting 06d_violin_histograms_from_csv.R\n")
cat("====================================================\n\n")

###############################################################
# 0 — LIBRARIES
###############################################################

suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(stringr)
})

###############################################################
# 1 — PATHS
###############################################################

csv_root <- "output/angles_helices/angles/angle_csv"

out_violin <- "output/angles_helices/angles/distributions2/violins"
out_hist   <- "output/angles_helices/angles/distributions2/histograms"

dir.create(out_violin, recursive=TRUE, showWarnings=FALSE)
dir.create(out_hist, recursive=TRUE, showWarnings=FALSE)

###############################################################
# 2 — SETTINGS
###############################################################

start_ns <- 10

apo_color  <- "white"
cap_color  <- "red"
heat_color <- "blue"

alpha_fill <- 0.55
bins_n <- 35

plot_title_size <- 15
axis_title_size <- 13
axis_text_size  <- 11

###############################################################
# 3 — ORDERS
###############################################################

mutant_order <- c("WT","W426A","W697A","Y441A")
cond_order   <- c("Apo","Cap","Heat")

full_order <- c(
  "WT Apo","WT Cap","WT Heat","",
  "W426A Apo","W426A Cap","W426A Heat"," ",
  "W697A Apo","W697A Cap","W697A Heat","  ",
  "Y441A Apo","Y441A Cap","Y441A Heat"
)

###############################################################
# 4 — FIND CSV FILES
###############################################################

csv_files <- list.files(
  csv_root,
  pattern="^angles_.*\\.csv$",
  recursive=TRUE,
  full.names=TRUE
)

cat("Found", length(csv_files), "CSV files\n")

###############################################################
# 5 — LOOP OVER ALL PAIRS
###############################################################

for(file in csv_files){
  
  pair_name <- str_remove(basename(file), "^angles_")
  pair_name <- str_remove(pair_name, "\\.csv$")
  
  cat("[", Sys.time(), "] Processing:", pair_name, "\n")
  
  ###########################################################
  # LOAD DATA
  ###########################################################
  
  df <- read.csv(file, stringsAsFactors=FALSE)
  
  df <- df %>%
    filter(time_ns >= start_ns) %>%
    mutate(
      pdb = sub("^(7LP9|7LPB|7LPC)_.*", "\\1", system),
      mutant = sub("^(7LP9|7LPB|7LPC)_", "", system),
      condition = case_when(
        pdb=="7LP9" ~ "Apo",
        pdb=="7LPB" ~ "Cap",
        pdb=="7LPC" ~ "Heat",
        TRUE ~ pdb
      ),
      label = paste(mutant, condition)
    )
  
  ###########################################################
  # VIOLIN PLOT
  ###########################################################
  
  df$label <- factor(df$label, levels=full_order)
  
  g1 <- ggplot(df,
               aes(x=label,
                   y=angle,
                   fill=condition)) +
    
    geom_violin(trim=FALSE,
                color="black",
                linewidth=0.3,
                alpha=0.7) +
    
    scale_fill_manual(
      values=c(
        "Apo"="white",
        "Cap"="red",
        "Heat"="blue"
      )
    ) +
    
    labs(
      title=paste("Distribution:", pair_name),
      x="System",
      y="Angle (degrees)"
    ) +
    
    theme_bw() +
    
    theme(
      plot.title=element_text(size=plot_title_size),
      axis.title=element_text(size=axis_title_size),
      axis.text.x=element_text(
        size=9,
        angle=45,
        hjust=1
      ),
      axis.text.y=element_text(size=axis_text_size),
      legend.position="none"
    )
  
  ggsave(
    filename=file.path(
      out_violin,
      paste0("violin_", pair_name, ".png")
    ),
    plot=g1,
    width=12,
    height=6,
    dpi=300
  )
  
  ###########################################################
  # HISTOGRAM PANELS
  ###########################################################
  
  df$mutant <- factor(df$mutant, levels=mutant_order)
  df$condition <- factor(df$condition, levels=cond_order)
  
  g2 <- ggplot(df, aes(x=angle)) +
    
    geom_histogram(
      data=df %>% filter(condition=="Apo"),
      bins=bins_n,
      fill="white",
      color="black",
      alpha=0.45,
      position="dodge"
    ) +
    
    geom_histogram(
      data=df %>% filter(condition=="Cap"),
      bins=bins_n,
      fill="red",
      color="black",
      alpha=alpha_fill,
      position="dodge"
    ) +
    
    geom_histogram(
      data=df %>% filter(condition=="Heat"),
      bins=bins_n,
      fill="blue",
      color="black",
      alpha=alpha_fill,
      position="dodge"
    ) +
    
    facet_wrap(
      ~mutant,
      ncol=2
    ) +
    
    labs(
      title=paste("Histograms:", pair_name),
      x="Angle (degrees)",
      y="Count"
    ) +
    
    theme_bw() +
    
    theme(
      plot.title=element_text(size=plot_title_size),
      axis.title=element_text(size=axis_title_size),
      axis.text=element_text(size=axis_text_size),
      strip.text=element_text(size=12)
    )
  
  ggsave(
    filename=file.path(
      out_hist,
      paste0("hist_", pair_name, ".png")
    ),
    plot=g2,
    width=10,
    height=8,
    dpi=300
  )
  
}

cat("\n====================================================\n")
cat("[", Sys.time(), "] Script finished successfully\n")
cat("====================================================\n")